### ISSUE TITLE
BUG: Staff Fighter ability breaks character sheets 

### ISSUE THREAD

**Issue by Flintwyrm** [pwatson100/symbaroum#220]
If you have weapons in your inventory and you add Staff Fighting it wont add the ability. if you f5 refresh it appears in your sheet but then your weapons dont show up and you cant add any weapons.

These are the errors
![Screenshot_2347](https://user-images.githubusercontent.com/60701064/126100802-8d20cd17-3faa-4a20-be42-6269561f8357.png)
![Screenshot_2348](https://user-images.githubusercontent.com/60701064/126100804-8e5fb2db-d8ae-43ee-9743-296f8cda3780.png)

I am using the most current Symbaroum and 0.8.8 Foundry. 

This is a big problem for my staff mage that cant have staffs XD I have a game next Sunday if it is possible to fix by that time.

**Comment by bithir** [comment]
A short term solution can be to disable the automatic handling of Staff Fighter. This can be done by enabling "Allow reference modification", and for the "Staff Fighter" ability for this character - just prefix the reference field with "disabled-". Once the fix is out, you can re-enable the normal functionality by just removing the prefix.

Note: you will need to cater for damage increase manually while fix is being worked on/pushed out in a release.
