### ISSUE TITLE
Combat enhancement - bug i calculation enemy damage

### ISSUE THREAD

**Issue by THZ74** [pwatson100/symbaroum#238]
(With combat enhancement disabled this bug disapear)

But with it enabled:

If an enemy hit you with a sword doing 1d8 damage it correctly does 4 damage
If an enemy has a deep impact sword doing 1d8+1 it correctly does 5 damage
If an enemy has a flaming sword doing +1d4 it correctly do 6 damage

If an enemy has a +2 damage sword (for some reason) it incorrectly do 5 damage (1d8->4 and 2->1)
If an enemy has a +3 or +4 sword it incorrectly does 6 damage   (1d8-> 4  and 3 or 4 ->2)

If an enemy has a flaming deep impact sword doing 1d8+1d4+1 in damage it makes that incorrectly (1d8->4 and 1d4+1 >2 or 3)

If an enemy attacks from advantage it correctly gets +2 damage.

Robust and Beserk is calculated correctly. (+2 and +3 respectively)

My guess?
Something in the calculation of enemy damage has a bug but only in CE. Since the +dam from Advantage/abilities is correctly calculated my guess is (I have no coding ability) that the code takes "all weapon and qualities damage" and divide it by two and round it off to the lower number. 
And afterwards add the +2 from Advantage,/abilities

Conclusion
Not gamebreaking, very rare for enemies to have +damage modifications above 1. Only instance is if they have elemental oil/ flaming and deep impact.

So not sure if its worth fixing or just something that should be written in known bugs?

Respectfully
THZ

**Comment by Khaali-dev** [comment]
Hello,
When entering data for weapons and armor, eveything must be entered as for a PC.
For exemple, in case of a sword coated with elemental essence, a bonus of +1d4 should be typed in the "bonus damage field". This sword can then be given to either a PC or a NPC. If use by a PC, the damage bonus will be +1d4, and if a NPC wields it it will automatically be +2
Code for calculating NPC's damage and armor value evaluate (maximum damage from PC dice / 2). Because as far as I know, every damage/armor bonuses works this way in Symbaroum. There are no +2 or +3 weapons.
The only exceptions are deep impact (weapons) and reinforced (armor) qualities that does a fixed +1 whether its a PC or an NPC using it.
Both deep impact and reinforced are treated separatly in the code and should be OK.

**Comment by Khaali-dev** [comment]
Hope this answers your question?

**Comment by THZ74** [comment]
Not close to my computer right now so can't check.
But I think i did all tests with the damage modification.
If deep impact works separately there is no bug. Just me entering numbers to see what happens

I think i wrote "elementar oil and deep impact as +1d4+1 instead of "deep impact" and +1d4 modification.

So as usual: the error is between the screen and backrest ;)

Respectfully
Thz

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________
