### ISSUE TITLE
Choose Attack stat

### ISSUE THREAD

**Issue by Pheromant** [pwatson100/symbaroum#647]
I am asking for an option in the settings of the EC that allows players to select the attribute for an attack instead of automatically taking the highest. Similar to the option to pick the attribute for initiative. 

Could be either directly on the character sheet or as an option in the attack related pop-up window (the one where you can choose to add poison, robust etc.) 

It becomes important for characters with more than one alternative attack stat.

**Comment by bithir** [comment]
I would like to note that this is unlikely to be implemented - the reason is that a change to support  conditional modifiers of attributes/attack value is highly unlikely.  At the moment the system picks the highest attribute of the candidate attributes for an attack - so just adding in another candidate attribute would not be sufficient, you would need to pass in some sort of override flag and cascade that down through the whole call stack.  

Picking the highest attribute works well for (almost?) all things, with the exception of Discreet, and then only if it is lower than 1 pt of accurate (the normal attack attribute).  This is because Feint has a conditional bonus through the Advantage it grants for when Discreet is used.

This can be worked around in multiple ways already in the system:
1) You could just add a modifier in your attack that compensates for the attribute difference (i.e. put a 1 in the modifier)
2) You could just set the weapon to have a different main-attribute than Accurate, for example Discreet (thus making the candidate attribute to be only Discreet)

We probably could accept a PR for it, but the amount of work and change for what can easily be changed or adjusted in the system makes this change unlikely to be implemented in the near time.

**Comment by bithir** [comment]
Can you confirm you are happy with doing it like this?

**Comment by Pheromant** [comment]
Sorry for keeping you waiting.
The second option will work best for me,i guess.
Thank you for answering 🍻
