### ISSUE TITLE
Active Effects support?

### ISSUE THREAD

**Issue by sirkerry** [pwatson100/symbaroum#660]
Would it be possible to add support for the core FVTT Active Effects?

**Comment by bithir** [comment]
Technically supported already but we provide no button to add/remove or edit active effects.

We have no current plans (but could change) on replacing the conditions and effects of abilities, powers and traits because:
1) Difficult to do because they are conditionals (only applies to this and that under these circumstances)
2) The bonus system was already added in the dawn of time and works most circumstances
3) Certain effects (dice upgrades from different sources) for classes of items/actors are not easily done with ActiveEffects
4) Most temporary effects are to "end of scene" and not turn or round based - there could be one or three combat encounters before a scene ends.

However, you could create a macro or similar to add/remove or edit active effects.  

I think if we are to invest in creating a framework for working with ActiveEffects that plugs in to the system, it would be useful for us to see what the use case is where you need it to meet the rules of Symbaroum or (if it is) modules that require them?

**Comment by bithir** [comment]
@sirkerry just bumping this. Would you be able to provide us with the use-case on where you think this is required?

**Comment by bithir** [comment]
Closing this issue
